### ISSUE TITLE
Токен не должен храниться в открытом виде

### ISSUE THREAD

**Issue by wooffie** [sergeyfedorov02/TelegramBotYouTube#19]
https://github.com/sergeyfedorov02/TelegramBotYouTube/blob/f6de8a6986fc4abc61c0ba9d8c406da4d9ce0b75/TelegramBotForYouTube/config.py#L1

**Comment by sergeyfedorov02** [comment]
Полностью с вами согласен, но это учебный проект, поэтому для его запуска требуется выкладывать все данные, чтобы преподавателю не пришлось осуществлять дополнительную генерацию.
